### PR TITLE
Update cookies.js for use in latest versions of pptr #78

### PR DESCRIPTION
**Pull request by smashah**
Relating to #78

### CODE REVIEW

**Comment by guy-bartkus** [comment]
Merge?

**Comment by ThinhVu** [comment]
> Merge?

You don't need to wait for the merge to use the patch. Add the line below to package.json:

`"puppeteer-page-proxy": "git+ssh://git@github.com:smashah/puppeteer-page-proxy#patch-1"`

**Comment by smashah** [comment]
thanks @ThinhVu I have merged the patch to the main branch on my fork's repo so you can also do this now:

```js
"puppeteer-page-proxy": "smashah/puppeteer-page-proxy"
```

Just F.Y.I, feel free to make a PR on [smashah/puppeteer-page-proxy](https://github.com/smashah/puppeteer-page-proxy) I will try to review quickly and merge if relevant.

**Comment by TimRChen** [comment]
wish this PR counld merge early.

**Comment by ThinhVu** [comment]
> thanks @ThinhVu I have merged the patch to the main branch on my fork's repo so you can also do this now:
> 
> ```js
> "puppeteer-page-proxy": "smashah/puppeteer-page-proxy"
> ```
> 
> Just F.Y.I, feel free to make a PR on [smashah/puppeteer-page-proxy](https://github.com/smashah/puppeteer-page-proxy) I will try to review quickly and merge if relevant.

Oh. I don't even know that we can use that short form. Nice.

**Pull request merged**
